# Generated by Django 2.0.1 on 2018-04-10 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0003_message_is_hidden'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=200)),
                ('salary', models.FloatField()),
            ],
        ),
    ]
