# Generated by Django 2.0.1 on 2018-04-12 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0005_credit_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit_card',
            name='number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
