# Generated by Django 2.0.1 on 2018-05-11 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0011_food'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
    ]
