# Generated by Django 2.0.1 on 2018-05-15 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0014_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_Completed',
            field=models.BooleanField(default=False),
        ),
    ]
