# Generated by Django 2.0.1 on 2018-05-15 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0015_task_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='test',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
