# Generated by Django 2.0.1 on 2018-06-19 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0017_auto_20180515_0317'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task_Ajax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=200)),
            ],
        ),
    ]
