# Generated by Django 2.0.1 on 2018-06-22 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0019_comment_ajax'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ajax_Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=200)),
                ('priority', models.IntegerField()),
                ('is_completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Comment_Ajax',
        ),
        migrations.DeleteModel(
            name='Task_Ajax',
        ),
    ]
