# Generated by Django 2.0.1 on 2018-07-14 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0020_auto_20180622_0219'),
    ]

    operations = [
        migrations.CreateModel(
            name='Superhero2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('superpower', models.CharField(max_length=100)),
                ('is_good', models.BooleanField()),
                ('is_male', models.BooleanField()),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
